import { Hono } from 'hono';
const app = new Hono<{ Bindings: { DB: D1Database } }>();

app.get('/sessions/:eid', async (c) => {
  const eid = c.req.param('eid');
  const { results } = await c.env.DB.prepare(
    'SELECT s.id,s.title,s.session_date,s.start_time,s.end_time,s.max_capacity,l.name as location_name,(SELECT COUNT(*) FROM participant_sessions WHERE session_id=s.id) as booked,(SELECT COUNT(*) FROM participant_sessions WHERE session_id=s.id AND attended=1) as attended FROM sessions s LEFT JOIN locations l ON l.id=s.location_id WHERE s.event_id=? ORDER BY s.session_date,s.start_time'
  ).bind(eid).all();
  return c.json(results);
});

app.get('/survey/:eid', async (c) => {
  const eid = c.req.param('eid');
  const s = (await c.env.DB.prepare('SELECT id,title,questions FROM surveys WHERE event_id=?').bind(eid).first()) as any;
  if (!s) return c.json({});;
  const { results } = await c.env.DB.prepare(
    'SELECT r.*,p.name as participant_name FROM survey_responses r JOIN participants p ON p.id=r.participant_id WHERE r.survey_id=? ORDER BY r.submitted_at'
  ).bind(s.id).all();
  const questions = JSON.parse((s.questions as string)||'[]');
  const analytics: any = {};
  for (const q of questions) {
    const counts: Record<string, number> = {};
    for (const r of results as any[]) {
      const ans = JSON.parse((r.answers as string)||'{}');
      const val = ans[q.id];
      if (val !== undefined && val !== null) counts[String(val)] = (counts[String(val)]||0) + 1;
    }
    analytics[q.id] = { question: q.question, type: q.type, counts };
  }
  return c.json({ title: s.title, total: results.length, analytics });
});

app.get('/export/full/:eid', async (c) => {
  const eid = c.req.param('eid');
  const ev = (await c.env.DB.prepare('SELECT * FROM events WHERE id=?').bind(eid).first()) as any;
  const parts = await c.env.DB.prepare(
    'SELECT p.name,p.phone,p.email,p.company,p.status,h.name as hotel_name,r.room_number,b.label as bed_label FROM participants p LEFT JOIN hotels h ON h.id=p.hotel_id LEFT JOIN beds b ON b.id=p.bed_id LEFT JOIN rooms r ON r.id=b.room_id WHERE p.event_id=? ORDER BY p.name'
  ).bind(eid).all();
  const sessions = await c.env.DB.prepare(
    'SELECT s.title,s.session_date,s.start_time,s.end_time,l.name as location_name,(SELECT COUNT(*) FROM participant_sessions WHERE session_id=s.id) as booked FROM sessions s LEFT JOIN locations l ON l.id=s.location_id WHERE s.event_id=? ORDER BY s.session_date,s.start_time'
  ).bind(eid).all();
  // Generate HTML report
  let rows = (parts.results as any[]).map((p:any) => `<tr><td>${p.name}</td><td>${p.hotel_name||'-'}</td><td>${p.room_number||'-'}/${p.bed_label||'-'}</td><td>${p.status}</td></tr>`).join('');
  let srows = (sessions.results as any[]).map((s:any) => `<tr><td>${s.title}</td><td>${s.session_date}</td><td>${s.start_time}-${s.end_time}</td><td>${s.location_name||'-'}</td><td>${s.booked||0}</td></tr>`).join('');
  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${ev?.name || 'Report'} - Full Report</title><style>
    body{font-family:sans-serif;padding:20px;color:#333}
    h1{color:#1a1b1e;border-bottom:2px solid #4c6ef5}
    table{width:100%;border-collapse:collapse;margin:12px 0}
    th,td{padding:8px;text-align:left;border-bottom:1px solid #eee}
    th{background:#4c6ef5;color:white}
    .section{margin:24px 0}
    @media print{body{padding:0}}
  </style></head><body>
    <h1>${ev?.name || 'Report'}</h1>
    <p>${ev?.start_date || ''} to ${ev?.end_date || ''} &mdash; ${ev?.event_code || ''}</p>
    <div class="section"><h2>Participants (${parts.results.length})</h2><table><thead><tr><th>Name</th><th>Hotel</th><th>Room</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table></div>
    <div class="section"><h2>Sessions (${sessions.results.length})</h2><table><thead><tr><th>Session</th><th>Date</th><th>Time</th><th>Location</th><th>Booked</th></tr></thead><tbody>${srows}</tbody></table></div>
    <p style="margin-top:32px;font-size:12px;color:#999">Generated by HMS &mdash; ${new Date().toLocaleDateString()}</p>
  </body></html>`;
  return c.newResponse(html, { headers: {'Content-Type':'text/html','Cache-Control':'no-cache'} });
});

export { app as reportExtRoutes };
